export const colors = {
  black: 'var(--color-black)',
  blackSoft: 'var(--color-black-soft)',
  red: 'var(--color-red)',
  redHover: 'var(--color-red-hover)',
  white: 'var(--color-white)',
  whiteMuted: 'var(--color-white-muted)',
  charcoalDeep: 'var(--color-charcoal-deep)',
  charcoalSurface: 'var(--color-charcoal-surface)',
  charcoalPanel: 'var(--color-charcoal-panel)',
  offWhite: 'var(--color-off-white)',
  offWhiteMuted: 'var(--color-off-white-muted)',
  copper: 'var(--color-copper)',
  copperLight: 'var(--color-copper-light)',
  copperDark: 'var(--color-copper-dark)',
  steel: 'var(--color-steel)',
  steelDark: 'var(--color-steel-dark)',
  steelDeep: 'var(--color-steel-deep)',
  error: 'var(--color-error)',
  errorBorder: 'var(--color-error-border)',
  errorBg: 'var(--color-error-bg)',
} as const;
